### ISSUE TITLE
Error running sample code Python 32bit

### ISSUE THREAD

**Issue by royalone** [MrThearMan/filedialogs#1]
Error as described below when running the simple example provided:

```
(32 VENV) C:\...\32 VENV\Builds\test\qt\windows_filedialog>filedialog_test.py
Traceback (most recent call last):
  File "C:\...\32 VENV\Builds\test\qt\windows_filedialog\filedialog_test.py", line 1, in <module>
    from filedialogs import save_file_dialog, open_file_dialog, open_folder_dialog
  File "C:\...\32 VENV\lib\site-packages\filedialogs\__init__.py", line 1, in <module>
    from . filedialogs import  *
  File "C:\...\32 VENV\lib\site-packages\filedialogs\filedialogs.py", line 20, in <module>
    ext: str = "All Files\0*.*\0", multiselect: bool = False) -> Union[list[str], str, None]:
TypeError: 'type' object is not subscriptable
```

I'm using a python 3.8.7 32bit virtual environment in the screenshot above. Same result if running standard installation 32 bit python. Works fine in Python 3.9.1 x64. I pip installed pypiwin32 on all. I'm also using Windows 10 Pro 10.0.19042 Build 19042.
Not a big issue for me, just reporting it. Thanks for sharing!

**Comment by MrThearMan** [comment]
Thanks for using my project!

I refactored the code to work on python 3.8, new version should be up on PyPI. I made some other quality of life imprevements as well, mainly [this](https://github.com/MrThearMan/filedialogs/commit/3c874ba7c0e04a0aae62bbb26a7b4316c6b35be0#diff-c3b40692a268afc6fdcd88d3df1156e210c33dd51310d0dde1a0587383e6eb5aR32) and [this](https://github.com/MrThearMan/filedialogs/commit/3c874ba7c0e04a0aae62bbb26a7b4316c6b35be0#diff-c3b40692a268afc6fdcd88d3df1156e210c33dd51310d0dde1a0587383e6eb5aR94), so you can input the desired file formats as list of tuples instead of strings.

**Comment by royalone** [comment]
Cheers for the fast response, works great now
